Feature
canon20paul/My-Portfolio-setup-Desktop-version pull request #1
Opened 2022-07-09 13:03 UTC by canon20paul

First phase of developing Portfolio Desktop Version with @media Queries foe Mobile Devices

2022-07-09 16:41 UTC, BertrandConxy requested changes
Hi @canon20paul , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💪 
- No linter errors
- Descriptive PR
- Project works well on my pc
- good README


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 16:41 UTC, BertrandConxy commented on index.html
> +                      </div>
- [ ] NOTE that this nav list should not be visible on the mobile screens. We will only be having a hamburger icon. I noticed that on your design when it is on mobile screens, these nav items are visible which is not correct based on the Figma design you chose. Look at the screenshot below 👇 
![image](https://user-images.githubusercontent.com/90222110/178113616-62dbf4fe-dcbb-4df6-9463-c29768cd6fb1.png)
Please use media queries in order to handle styles of elements depending on the window screen sizes which will make your portfolio responsive 😃.

2022-07-09 16:41 UTC, BertrandConxy commented on index.html
> +        <ul class="L3">
- [ ] We should apply HTML best practices as it in the requirements and among them, there is the one which tell us to use the correct indentation in our HTML codes. Please go back and read about them then use the correct indentation here and in all your HTML 🏃.

2022-07-09 16:41 UTC, BertrandConxy commented on index.html
> +    </nav>
- [ ] Your social media icons look great 👏. However, in your HTML, you have used inappropriate tags. These social media icons are not supposed to be contained in a nav tag. Imagine having more than one navigation in one page 🤔. This is inappropriate and in addition, it will be interpreted wrongly by the screen readers and other accessibility devices. That is why the use of semantic tags in the appropriate way is necessary. Please remove these social media icons from the nav tag instead you can let them remain wrapped in a `div` then style them again very well.

2022-07-09 16:41 UTC, BertrandConxy commented on index.html
> +    </nav>
- [ ] There are some details that you forgot to implement on your design. Look at the comparison below 👇
**Figma design**
![image](https://user-images.githubusercontent.com/90222110/178114374-1da89243-c30d-4237-8bf4-4906c660342f.png)
**Your work**
![image](https://user-images.githubusercontent.com/90222110/178114411-acb2cb17-a51a-4b63-85a3-abdd9fa2fe25.png)
Attention to all details is an important skill that a developer should have. Please try to implement all the details on the Figma design as they help your portfolio look great 😃.

2022-07-09 16:41 UTC, BertrandConxy commented on index.css
> +}
- [ ] Your buttons look great 👏. In addition to what you have done so far, I would suggest you implement the correct styles for user interaction. I have seen that the color changes on hover, however, it is styled the correct way. There need to be some improvements 😃. Please refer to the details given in the Figmaa design and then implement all the necessary button interactions. Here is a screenshot of what they should look like 👇 
![image](https://user-images.githubusercontent.com/90222110/178114700-bf83f14e-9893-4497-8dc4-6c913307b620.png)

2022-07-09 16:41 UTC, BertrandConxy commented on index.html
> +            <h2 class="f">My recent Work</h2>
- [ ] I think you have noticed that there is really a very long space below your footer which is supposed to be the last part of your portfolio. I realized that it is due to the styles you have given to this heading `h2` that it looks like it has the extended height that it's supposed to have. While I don't know really what is the cause so far, I would suggest you try to fix it. Look at your design 👇 
![image](https://user-images.githubusercontent.com/90222110/178114894-f4bec457-c633-452b-8ec4-4684647ae1a8.png)

2022-07-09 19:06 UTC, Ismailco reviewed
Hi @canon20paul, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has some linter errors, kindly fix them first

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-09 21:12 UTC, MeqdamAlqudah requested changes
Hi @canon20paul , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 21:12 UTC, MeqdamAlqudah commented on .github/workflows/linters.yml
> +    runs-on: ubuntu-18.04
- [ ] Please as the last reviewer said fix the white space that appears after the footer
![image](https://user-images.githubusercontent.com/74744787/178122598-51460725-c0ef-4598-9873-811aa3d0eaf6.png)

2022-07-09 21:12 UTC, MeqdamAlqudah commented on .github/workflows/linters.yml
> +    runs-on: ubuntu-18.04
- [ Optional ] Please the work button that you add should send the user to the work section 
![image](https://user-images.githubusercontent.com/74744787/178122658-6060d376-258c-4836-9a4f-0243569de718.png)

2022-07-09 21:12 UTC, MeqdamAlqudah commented on .github/workflows/linters.yml
> +        with:
- [ ] Please as the last reviewer said the social media icons should be listed in a `ul` tag

![image](https://user-images.githubusercontent.com/74744787/178122691-725b4a1c-e523-4b8b-b592-289355fc62af.png)

2022-07-09 21:12 UTC, MeqdamAlqudah commented on .github/workflows/linters.yml
> +        run: npm install -g @lhci/cli@0.7.x
- [ ] Please the menu options should disappear when the user uses the mobile version
![image](https://user-images.githubusercontent.com/74744787/178122748-2eec0b80-34a4-42d2-8d6d-d3e16870fce0.png)

2022-07-09 21:12 UTC, MeqdamAlqudah commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] as the last reviewer said please remove this additional line in the Readme file

2022-07-14 08:33 UTC, muneebulrehman requested changes
Hi @canon20paul , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 08:33 UTC, muneebulrehman commented on index.html
> +          <div class="Footer flame">
There is a whole page of blank space trailing at the end of the footer. Consider removing this. 
![image](https://user-images.githubusercontent.com/33268927/178935092-b4a7e228-0a05-45ac-abab-056c51d55dd5.png)

2022-07-14 08:33 UTC, muneebulrehman commented on index.html
> +    <nav class="nav1 flame">
Consider fixing the spacing issues and try to make the layout exactly as the Figma design.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/178936112-32353aa9-b0ba-4749-8eec-e7f630eb2f0e.png) | ![image](https://user-images.githubusercontent.com/33268927/178935993-5faa40f1-e5cd-4733-af73-363008262230.png) |

2022-07-14 08:33 UTC, muneebulrehman commented on index.html
> +    <section class="section1 flame">
Consider adding some margin to the top of this section as in the Figma design.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/178936546-988cfbee-8bdb-4551-9eb3-d8ba7f848fa5.png) | ![image](https://user-images.githubusercontent.com/33268927/178936379-269713af-5849-4848-9621-f88bd6df10b7.png) |

2022-07-14 08:33 UTC, muneebulrehman commented on index.html
> +            <form
The layout of the form for the desktop screen is not matching. Also, you should have two separate fields for the name. One for the first name and one for the last name. Consider fixing it and also give it a proper placeholder value. Please consider using the same margins and padding values as in the Figma template.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/178938156-36f1c694-6661-422a-990f-1c52698a7b26.png) | ![image](https://user-images.githubusercontent.com/33268927/178938036-ceb23943-7467-44ea-8203-b4f626a7987e.png) |

2022-07-14 08:33 UTC, muneebulrehman commented on index.css
> +@media (max-width: 77rem) {
`min-width` for larger devices should be 768px and above. Consider making it the same.

2022-07-14 13:00 UTC, rukundoeric requested changes
Hello @canon20paul 👋,

_This is an additional review as a result of the second opinion request._

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._

## Required Changes ♻️
_Check the comments under the review._

Keep rocking 🚀!

2022-07-14 13:48 UTC, canon20paul commented on index.html
> +              ><br />
kindly which part of the project gives this. I can't find it

2022-07-14 14:58 UTC, canon20paul commented on index.html
> +    <nav class="nav1 flame">
Hi Eric,
Much thanks. Kindly that my First Page. its what i pushed, Am confused by what you have indicated above. Pliz advise accordingly.
thank you

![Screenshot (19)](https://user-images.githubusercontent.com/106068714/179012199-bbf9d75c-3653-4c86-9b03-48574633efdf.png)

2022-07-14 15:01 UTC, canon20paul commented on index.html
> +              ><br />
Hello again,
Please be patient with me as i need to get this right. kindly contrast and advise accordingly
![Screenshot (20)](https://user-images.githubusercontent.com/106068714/179013601-26b7aef2-a461-4bc4-944e-d5a3f9cfe774.png)

2022-07-15 12:13 UTC, Bondok6 commented on .vscode/settings.json
> +}
[OPTIONAL] since this is your   own VSCode setting. it doesn't necessarily need to be committed into the repo. so having this in the .gitignore file may be a good choice 👍

2022-07-15 13:51 UTC, merged